/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_pruebas_02_loro_carlos_zaragoza;

import java.awt.Color;
import java.awt.Font;
import java.awt.color.ColorSpace;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author carlo
 */
public class interfaz_loro extends javax.swing.JFrame {

    /**
     * Creates new form interfaz_loro
     */
    
    Font normal = new Font("Arial",Font.PLAIN,16);
    Font negrita = new Font("Arial",Font.BOLD,16);
    
    
    
    public interfaz_loro() {
        initComponents();
   
        rgTamanio.add(rbFijo);
        rgTamanio.add(rbRedimensionar);
        
        rgAlineacion.add(rbLeft);
        rgAlineacion.add(rbJustificada);
        rgAlineacion.add(rbRight);
    
        bgColors.add(rbBlue);
        bgColors.add(rbOrange);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_salir = new javax.swing.JDialog();
        jpn_dialogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        rgTamanio = new javax.swing.ButtonGroup();
        rgAlineacion = new javax.swing.ButtonGroup();
        bgColors = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        txfActions = new javax.swing.JTextField();
        labelCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbFijo = new javax.swing.JRadioButton();
        rbRedimensionar = new javax.swing.JRadioButton();
        chb_negrita = new javax.swing.JCheckBox();
        cboxMayusculas = new javax.swing.JCheckBox();
        sld_num = new javax.swing.JSlider();
        rbLeft = new javax.swing.JRadioButton();
        rbJustificada = new javax.swing.JRadioButton();
        rbRight = new javax.swing.JRadioButton();
        rbOrange = new javax.swing.JRadioButton();
        rbBlue = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMaximizar = new javax.swing.JMenu();
        mnMinimizar = new javax.swing.JMenu();

        dlg_salir.setMinimumSize(new java.awt.Dimension(300, 200));
        dlg_salir.setModal(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Se cerrara el programa, ¿desea continuar?");

        btn_cerrar.setText("Si");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("No");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_dialogoLayout = new javax.swing.GroupLayout(jpn_dialogo);
        jpn_dialogo.setLayout(jpn_dialogoLayout);
        jpn_dialogoLayout.setHorizontalGroup(
            jpn_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_dialogoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        jpn_dialogoLayout.setVerticalGroup(
            jpn_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_dialogoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpn_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlg_salirLayout = new javax.swing.GroupLayout(dlg_salir.getContentPane());
        dlg_salir.getContentPane().setLayout(dlg_salirLayout);
        dlg_salirLayout.setHorizontalGroup(
            dlg_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_dialogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dlg_salirLayout.setVerticalGroup(
            dlg_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_dialogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 519));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Superior"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(txfActions);

        labelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close.png"))); // NOI18N
        labelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(labelCerrar);

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Inferior"));
        jPanel2.setLayout(new java.awt.GridLayout(4, 3));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vulcan.png"))); // NOI18N
        jLabel3.setText("Saludar");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel3);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bye.png"))); // NOI18N
        jLabel2.setText("Despedirse");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);

        rbFijo.setText("Tamaño Fijo");
        rbFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFijoActionPerformed(evt);
            }
        });
        jPanel2.add(rbFijo);

        rbRedimensionar.setSelected(true);
        rbRedimensionar.setText("Redimensionar");
        rbRedimensionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRedimensionarActionPerformed(evt);
            }
        });
        jPanel2.add(rbRedimensionar);

        chb_negrita.setText("negrita");
        chb_negrita.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chb_negritaStateChanged(evt);
            }
        });
        chb_negrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_negritaActionPerformed(evt);
            }
        });
        jPanel2.add(chb_negrita);

        cboxMayusculas.setText("Mayusculas");
        cboxMayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMayusculasActionPerformed(evt);
            }
        });
        jPanel2.add(cboxMayusculas);

        sld_num.setMajorTickSpacing(10);
        sld_num.setMaximum(50);
        sld_num.setMinorTickSpacing(2);
        sld_num.setPaintLabels(true);
        sld_num.setPaintTicks(true);
        sld_num.setValue(12);
        sld_num.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tamanio Fuente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 10))); // NOI18N
        sld_num.setMaximumSize(new java.awt.Dimension(32767, 78));
        sld_num.setMinimumSize(new java.awt.Dimension(36, 78));
        sld_num.setName(""); // NOI18N
        sld_num.setPreferredSize(new java.awt.Dimension(200, 78));
        sld_num.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld_numStateChanged(evt);
            }
        });
        jPanel2.add(sld_num);

        rbLeft.setText("Izquierda");
        rbLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbLeftMouseClicked(evt);
            }
        });
        rbLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLeftActionPerformed(evt);
            }
        });
        jPanel2.add(rbLeft);

        rbJustificada.setText("Justificada");
        rbJustificada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJustificadaActionPerformed(evt);
            }
        });
        rbJustificada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbJustificadaKeyPressed(evt);
            }
        });
        jPanel2.add(rbJustificada);

        rbRight.setText("Derecha");
        rbRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRightActionPerformed(evt);
            }
        });
        rbRight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbRightKeyPressed(evt);
            }
        });
        jPanel2.add(rbRight);

        rbOrange.setText("Orange");
        rbOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOrangeActionPerformed(evt);
            }
        });
        jPanel2.add(rbOrange);

        rbBlue.setText("Blue");
        rbBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBlueActionPerformed(evt);
            }
        });
        jPanel2.add(rbBlue);

        jSplitPane1.setRightComponent(jPanel2);

        mnMaximizar.setText("Maximizar");
        mnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMaximizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnMaximizar);

        mnMinimizar.setText("Minimizar");
        mnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMinimizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnMinimizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.pack();
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        dlg_salir.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void labelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseClicked
        txfActions.setText("El sistema se cerrara");
        openDialog();
    }//GEN-LAST:event_labelCerrarMouseClicked

    private void mnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMaximizarMouseClicked
        // TODO add your handling code here:
        interfaz_loro.this.setExtendedState(interfaz_loro.MAXIMIZED_BOTH);
    }//GEN-LAST:event_mnMaximizarMouseClicked

    private void mnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMinimizarMouseClicked
         interfaz_loro.this.setExtendedState(WIDTH);
    }//GEN-LAST:event_mnMinimizarMouseClicked

    private void rbRedimensionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRedimensionarActionPerformed
        // TODO add your handling code here:
        interfaz_loro.this.setResizable(true);
    }//GEN-LAST:event_rbRedimensionarActionPerformed

    private void rbFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFijoActionPerformed
        // TODO add your handling code here:
        interfaz_loro.this.setResizable(false);
    }//GEN-LAST:event_rbFijoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        txfActions.setText("Hasta Luego!!");
        if(chb_negrita.isSelected()){
            txfActions.setFont(negrita);
            txfActions.setText(txfActions.getText().toUpperCase());
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void chb_negritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_negritaActionPerformed
        // TODO add your handling code here:
        txfActions.setFont(normal);
        txfActions.setText(txfActions.getText());
        if(chb_negrita.isSelected()){
            txfActions.setFont(negrita);
            txfActions.setText(txfActions.getText().toUpperCase());
        }
    }//GEN-LAST:event_chb_negritaActionPerformed

    private void chb_negritaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chb_negritaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chb_negritaStateChanged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
 
        txfActions.setText("Buenas!!");
        if(chb_negrita.isSelected()){
            txfActions.setFont(negrita);
            txfActions.setText(txfActions.getText().toUpperCase());
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void sld_numStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld_numStateChanged
        // TODO add your handling code here:
        Font nueva = new Font("Arial",Font.PLAIN,sld_num.getValue());
        txfActions.setFont(nueva);
    }//GEN-LAST:event_sld_numStateChanged

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void rbLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbLeftMouseClicked

 
    }//GEN-LAST:event_rbLeftMouseClicked

    private void rbJustificadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbJustificadaKeyPressed

    }//GEN-LAST:event_rbJustificadaKeyPressed

    private void rbRightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbRightKeyPressed
   
    }//GEN-LAST:event_rbRightKeyPressed

    private void rbLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLeftActionPerformed
        // TODO add your handling code here:
        left();
    }//GEN-LAST:event_rbLeftActionPerformed

    private void rbJustificadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJustificadaActionPerformed
        // TODO add your handling code here:
        center();
    }//GEN-LAST:event_rbJustificadaActionPerformed

    private void rbRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRightActionPerformed
        // TODO add your handling code here:
        right();
    }//GEN-LAST:event_rbRightActionPerformed

    private void cboxMayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMayusculasActionPerformed
        // TODO add your handling code here:
      if(cboxMayusculas.isSelected()){
          
            txfActions.setText(txfActions.getText().toUpperCase());
      }else{
            txfActions.setText(txfActions.getText().toLowerCase());
      }
    }//GEN-LAST:event_cboxMayusculasActionPerformed

    private void rbOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOrangeActionPerformed
        // TODO add your handling code here:
        changeOrange();
    }//GEN-LAST:event_rbOrangeActionPerformed

    private void rbBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBlueActionPerformed
        // TODO add your handling code here:
        changeBlue();
    }//GEN-LAST:event_rbBlueActionPerformed

    private void changeOrange(){
       txfActions.setForeground(Color.ORANGE);
    }
    
    private void changeBlue(){
        txfActions.setForeground(Color.BLUE);

    }
    
    private void left(){txfActions.setHorizontalAlignment(JTextField.LEFT);}
    private void center(){ txfActions.setHorizontalAlignment(JTextField.CENTER);}
    private void right(){  txfActions.setHorizontalAlignment(JTextField.RIGHT);}
    
    private void openDialog(){
        dlg_salir.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_loro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_loro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_loro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_loro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_loro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgColors;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JCheckBox cboxMayusculas;
    private javax.swing.JCheckBox chb_negrita;
    private javax.swing.JDialog dlg_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jpn_dialogo;
    private javax.swing.JLabel labelCerrar;
    private javax.swing.JMenu mnMaximizar;
    private javax.swing.JMenu mnMinimizar;
    private javax.swing.JRadioButton rbBlue;
    private javax.swing.JRadioButton rbFijo;
    private javax.swing.JRadioButton rbJustificada;
    private javax.swing.JRadioButton rbLeft;
    private javax.swing.JRadioButton rbOrange;
    private javax.swing.JRadioButton rbRedimensionar;
    private javax.swing.JRadioButton rbRight;
    private javax.swing.ButtonGroup rgAlineacion;
    private javax.swing.ButtonGroup rgTamanio;
    private javax.swing.JSlider sld_num;
    private javax.swing.JTextField txfActions;
    // End of variables declaration//GEN-END:variables
}
