/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import elemento.AlumnoDetalle;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import utilidades.CSVReader;
import utilidades.CSVWriter;

/**
 *
 * @author usumaniana
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    private boolean verifyTitles = false;

    CSVReader CsvReader = new CSVReader();
    CSVWriter CsvWriter = new CSVWriter();

    private String currentProvincia = "";

    private DefaultListModel dflAlumnos = new DefaultListModel();
    private ArrayList<AlumnoDetalle> almacenAlumnos = new ArrayList<AlumnoDetalle>();

    public PaginaPrincipal() throws Exception {
        initComponents();

        bg_Provincias.add(rb_albacete);
        bg_Provincias.add(rb_cuenca);
        bg_Provincias.add(rb_guadalajara);
        bg_Provincias.add(rb_toledo);
        bg_Provincias.add(rb_ciudadReal);
        bg_Provincias.add(rbOtra);

        txf_Provincia.setEnabled(false);

        list_alumnos.setModel(dflAlumnos);

        almacenAlumnos = CsvReader.readCsvFile("src/elemento/DATA.CSV");

        rellenarList(almacenAlumnos);

    }

    public void rellenarList(ArrayList<AlumnoDetalle> listaAlumnos) {
        dflAlumnos.clear();

        for (AlumnoDetalle alm : listaAlumnos) {
            dflAlumnos.addElement(alm);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_crearAlumno = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        panel_primeraParte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txf_codigoPostal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txf_Provincia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txf_curso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txf_fecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txf_mail = new javax.swing.JTextField();
        panel_segundaParte = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rb_albacete = new javax.swing.JRadioButton();
        rb_toledo = new javax.swing.JRadioButton();
        rb_ciudadReal = new javax.swing.JRadioButton();
        rb_guadalajara = new javax.swing.JRadioButton();
        rb_cuenca = new javax.swing.JRadioButton();
        rbOtra = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_crear = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        bg_Provincias = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jMenu3 = new javax.swing.JMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_alumnos = new javax.swing.JList<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        dialog_crearAlumno.setMinimumSize(new java.awt.Dimension(750, 600));
        dialog_crearAlumno.getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        panel_primeraParte.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Alumno"));
        panel_primeraParte.setLayout(new java.awt.GridLayout(8, 2, 0, 10));

        jLabel2.setText("Nombre");
        panel_primeraParte.add(jLabel2);
        panel_primeraParte.add(txf_nombre);

        jLabel3.setText("Apellidos");
        panel_primeraParte.add(jLabel3);
        panel_primeraParte.add(txf_apellidos);

        jLabel4.setText("Direccion");
        panel_primeraParte.add(jLabel4);
        panel_primeraParte.add(txf_direccion);

        jLabel5.setText("Codigo postal");
        panel_primeraParte.add(jLabel5);
        panel_primeraParte.add(txf_codigoPostal);

        jLabel6.setText("Provincia");
        panel_primeraParte.add(jLabel6);
        panel_primeraParte.add(txf_Provincia);

        jLabel7.setText("Curso");
        panel_primeraParte.add(jLabel7);
        panel_primeraParte.add(txf_curso);

        jLabel8.setText("Fecha");
        panel_primeraParte.add(jLabel8);
        panel_primeraParte.add(txf_fecha);

        jLabel9.setText("Mail");
        panel_primeraParte.add(jLabel9);
        panel_primeraParte.add(txf_mail);

        jPanel5.add(panel_primeraParte);

        panel_segundaParte.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincias"));
        jPanel6.setLayout(new java.awt.GridLayout(6, 1));

        rb_albacete.setText("Albacete");
        rb_albacete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_albaceteMouseClicked(evt);
            }
        });
        jPanel6.add(rb_albacete);

        rb_toledo.setText("Toledo");
        rb_toledo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_toledoMouseClicked(evt);
            }
        });
        jPanel6.add(rb_toledo);

        rb_ciudadReal.setText("Ciudad Real");
        rb_ciudadReal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_ciudadRealMouseClicked(evt);
            }
        });
        jPanel6.add(rb_ciudadReal);

        rb_guadalajara.setText("Guadalajara");
        rb_guadalajara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_guadalajaraMouseClicked(evt);
            }
        });
        jPanel6.add(rb_guadalajara);

        rb_cuenca.setText("Cuenca");
        rb_cuenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_cuencaMouseClicked(evt);
            }
        });
        jPanel6.add(rb_cuenca);

        rbOtra.setText("Otra");
        rbOtra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbOtraItemStateChanged(evt);
            }
        });
        rbOtra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbOtraStateChanged(evt);
            }
        });
        rbOtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbOtraMouseClicked(evt);
            }
        });
        jPanel6.add(rbOtra);

        panel_segundaParte.add(jPanel6);

        jPanel5.add(panel_segundaParte);

        dialog_crearAlumno.getContentPane().add(jPanel5);

        menu_crear.setText("Añadir Alumno");
        menu_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_crearMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_crear);

        dialog_crearAlumno.setJMenuBar(jMenuBar1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Alumnos Creados");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(jPanel1);

        list_alumnos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(list_alumnos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jMenu1.setText("Crear Alumnos");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_albaceteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_albaceteMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("02")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
        if (rb_albacete.isSelected()) {
            currentProvincia = "Albacete";
        }

    }//GEN-LAST:event_rb_albaceteMouseClicked

    private void rb_toledoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_toledoMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("45")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
        if (rb_toledo.isSelected()) {
            currentProvincia = "Toledo";
        }
    }//GEN-LAST:event_rb_toledoMouseClicked

    private void rb_ciudadRealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_ciudadRealMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("13")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
        if (rb_ciudadReal.isSelected()) {
            currentProvincia = "Ciudad Real";
        }
    }//GEN-LAST:event_rb_ciudadRealMouseClicked

    private void rb_guadalajaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_guadalajaraMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("19")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
        if (rb_guadalajara.isSelected()) {
            currentProvincia = "Guadalajara";
        }
    }//GEN-LAST:event_rb_guadalajaraMouseClicked

    private void rb_cuencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_cuencaMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("16")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
        if (rb_cuenca.isSelected()) {
            currentProvincia = "Cuenca";
        }
    }//GEN-LAST:event_rb_cuencaMouseClicked


    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dialog_crearAlumno.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void rbOtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbOtraMouseClicked
        // TODO add your handling code here:
        if (rbOtra.isSelected() && txf_Provincia.getText().length() > 0) {
            currentProvincia = txf_Provincia.getText();
        }

    }//GEN-LAST:event_rbOtraMouseClicked

    private void rbOtraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbOtraStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOtraStateChanged

    private void rbOtraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbOtraItemStateChanged
        // TODO add your handling code here:
        if (rbOtra.isSelected()) {
            txf_Provincia.setEnabled(true);
        } else {
            txf_Provincia.setEnabled(false);
        }
    }//GEN-LAST:event_rbOtraItemStateChanged

    private void menu_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_crearMouseClicked
        // TODO add your handling code here:

        if (txf_direccion.getText().length() > 0
                && txf_nombre.getText().length() > 0
                && txf_apellidos.getText().length() > 0
                && txf_codigoPostal.getText().length() > 0
                && txf_curso.getText().length() > 0 
                && txf_mail.getText().length() > 0
                && txf_fecha.getText().length() > 0) {
            if (currentProvincia.length() > 0) {
                añadirAlumno();
            } else {
                JOptionPane.showMessageDialog(null, "Introduzca una provincia!!!!",
                        "Hey!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Rellene todos los parametros!",
                    "Hey!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_menu_crearMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (list_alumnos.getSelectedIndex() != -1) {
            deleteAlumnos();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteAlumnos() {

        AlumnoDetalle alum = (AlumnoDetalle) dflAlumnos.get(list_alumnos.getSelectedIndex());
        almacenAlumnos.remove(alum);

        try {
            CsvWriter.writeToFile("src/elemento/DATA.CSV", almacenAlumnos);
        } catch (Exception ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        rellenarList(almacenAlumnos);

    }

    private void añadirAlumno() {

        AlumnoDetalle alumno = new AlumnoDetalle(txf_nombre.getText(),
                txf_apellidos.getText(),
                currentProvincia,
                txf_curso.getText(),
                txf_codigoPostal.getText(),
                txf_direccion.getText(),
                txf_fecha.getText(),
                txf_mail.getText());

        almacenAlumnos.add(alumno);

        try {
            CsvWriter.writeToFile("src/elemento/DATA.CSV", almacenAlumnos);
        } catch (Exception ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        rellenarList(almacenAlumnos);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PaginaPrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Provincias;
    private javax.swing.JDialog dialog_crearAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList<String> list_alumnos;
    private javax.swing.JMenu menu_crear;
    private javax.swing.JPanel panel_primeraParte;
    private javax.swing.JPanel panel_segundaParte;
    private javax.swing.JRadioButton rbOtra;
    private javax.swing.JRadioButton rb_albacete;
    private javax.swing.JRadioButton rb_ciudadReal;
    private javax.swing.JRadioButton rb_cuenca;
    private javax.swing.JRadioButton rb_guadalajara;
    private javax.swing.JRadioButton rb_toledo;
    private javax.swing.JTextField txf_Provincia;
    private javax.swing.JTextField txf_apellidos;
    private javax.swing.JTextField txf_codigoPostal;
    private javax.swing.JTextField txf_curso;
    private javax.swing.JTextField txf_direccion;
    private javax.swing.JTextField txf_fecha;
    private javax.swing.JTextField txf_mail;
    private javax.swing.JTextField txf_nombre;
    // End of variables declaration//GEN-END:variables
}
