/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_prueba_04_zaragoza_carlos.pkg_interfaz;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author usumaniana
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();

        bg_Provincias.add(rb_albacete);
        bg_Provincias.add(rb_cuenca);
        bg_Provincias.add(rb_guadalajara);
        bg_Provincias.add(rb_toledo);
        bg_Provincias.add(rb_ciudadReal);

        cbox_grupo.addItem("1");
        cbox_grupo.addItem("2");
        cbox_grupo.addItem("3");
        cbox_grupo.addItem("4");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_crearAlumno = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        panel_primeraParte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txf_apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txf_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txf_codigoPostal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txf_Provincia = new javax.swing.JTextField();
        panel_segundaParte = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_observaciones = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        rb_albacete = new javax.swing.JRadioButton();
        rb_toledo = new javax.swing.JRadioButton();
        rb_ciudadReal = new javax.swing.JRadioButton();
        rb_guadalajara = new javax.swing.JRadioButton();
        rb_cuenca = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_crear = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        bg_Provincias = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        dialog_datosAcademicos = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txf_curso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txf_titulosAnteriores = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbox_grupo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        dialog_crearAlumno.setMaximumSize(new java.awt.Dimension(750, 600));
        dialog_crearAlumno.setMinimumSize(new java.awt.Dimension(750, 600));
        dialog_crearAlumno.setPreferredSize(new java.awt.Dimension(750, 600));
        dialog_crearAlumno.getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        panel_primeraParte.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Alumno"));
        panel_primeraParte.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

        jLabel2.setText("Nombre");
        panel_primeraParte.add(jLabel2);
        panel_primeraParte.add(txf_nombre);

        jLabel3.setText("Apellidos");
        panel_primeraParte.add(jLabel3);
        panel_primeraParte.add(txf_apellidos);

        jLabel4.setText("Direccion");
        panel_primeraParte.add(jLabel4);
        panel_primeraParte.add(txf_direccion);

        jLabel5.setText("Codigo postal");
        panel_primeraParte.add(jLabel5);
        panel_primeraParte.add(txf_codigoPostal);

        jLabel6.setText("Provincia");
        panel_primeraParte.add(jLabel6);
        panel_primeraParte.add(txf_Provincia);

        jPanel5.add(panel_primeraParte);

        panel_segundaParte.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones"));

        jta_observaciones.setColumns(20);
        jta_observaciones.setRows(5);
        jScrollPane1.setViewportView(jta_observaciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
        );

        panel_segundaParte.add(jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincias"));
        jPanel6.setLayout(new java.awt.GridLayout(5, 1));

        rb_albacete.setText("Albacete");
        rb_albacete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_albaceteMouseClicked(evt);
            }
        });
        jPanel6.add(rb_albacete);

        rb_toledo.setText("Toledo");
        rb_toledo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_toledoMouseClicked(evt);
            }
        });
        jPanel6.add(rb_toledo);

        rb_ciudadReal.setText("Ciudad Real");
        rb_ciudadReal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_ciudadRealMouseClicked(evt);
            }
        });
        jPanel6.add(rb_ciudadReal);

        rb_guadalajara.setText("Guadalajara");
        rb_guadalajara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_guadalajaraMouseClicked(evt);
            }
        });
        jPanel6.add(rb_guadalajara);

        rb_cuenca.setText("Cuenca");
        rb_cuenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_cuencaMouseClicked(evt);
            }
        });
        jPanel6.add(rb_cuenca);

        panel_segundaParte.add(jPanel6);

        jPanel5.add(panel_segundaParte);

        dialog_crearAlumno.getContentPane().add(jPanel5);

        menu_crear.setText("Crear");
        jMenuBar1.add(menu_crear);

        dialog_crearAlumno.setJMenuBar(jMenuBar1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        dialog_datosAcademicos.setMaximumSize(new java.awt.Dimension(600, 400));
        dialog_datosAcademicos.setMinimumSize(new java.awt.Dimension(600, 400));
        dialog_datosAcademicos.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Datos Academicos");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new java.awt.GridLayout(3, 2, 10, 20));

        jLabel8.setText("Curso");
        jPanel9.add(jLabel8);
        jPanel9.add(txf_curso);

        jLabel9.setText("Titulos anteriores");
        jPanel9.add(jLabel9);
        jPanel9.add(txf_titulosAnteriores);

        jLabel10.setText("Grupo");
        jPanel9.add(jLabel10);

        jPanel9.add(cbox_grupo);

        javax.swing.GroupLayout dialog_datosAcademicosLayout = new javax.swing.GroupLayout(dialog_datosAcademicos.getContentPane());
        dialog_datosAcademicos.getContentPane().setLayout(dialog_datosAcademicosLayout);
        dialog_datosAcademicosLayout.setHorizontalGroup(
            dialog_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_datosAcademicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialog_datosAcademicosLayout.setVerticalGroup(
            dialog_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_datosAcademicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(200, 200));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(303, 500));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 10));

        jMenu1.setText("Alumnos");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Academicos");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_albaceteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_albaceteMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("02")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_rb_albaceteMouseClicked

    private void rb_toledoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_toledoMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("45")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rb_toledoMouseClicked

    private void rb_ciudadRealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_ciudadRealMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("13")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rb_ciudadRealMouseClicked

    private void rb_guadalajaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_guadalajaraMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("19")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rb_guadalajaraMouseClicked

    private void rb_cuencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_cuencaMouseClicked
        // TODO add your handling code here:
        if (!txf_codigoPostal.getText().startsWith("16")) {
            JOptionPane.showMessageDialog(null, "Inserte el codigo postal correcto!!",
                    "Hey!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rb_cuencaMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
             // TODO add your handling code here:
             dialog_crearAlumno.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        dialog_datosAcademicos.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Provincias;
    private javax.swing.JComboBox<String> cbox_grupo;
    private javax.swing.JDialog dialog_crearAlumno;
    private javax.swing.JDialog dialog_datosAcademicos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jta_observaciones;
    private javax.swing.JMenu menu_crear;
    private javax.swing.JPanel panel_primeraParte;
    private javax.swing.JPanel panel_segundaParte;
    private javax.swing.JRadioButton rb_albacete;
    private javax.swing.JRadioButton rb_ciudadReal;
    private javax.swing.JRadioButton rb_cuenca;
    private javax.swing.JRadioButton rb_guadalajara;
    private javax.swing.JRadioButton rb_toledo;
    private javax.swing.JTextField txf_Provincia;
    private javax.swing.JTextField txf_apellidos;
    private javax.swing.JTextField txf_codigoPostal;
    private javax.swing.JTextField txf_curso;
    private javax.swing.JTextField txf_direccion;
    private javax.swing.JTextField txf_nombre;
    private javax.swing.JTextField txf_titulosAnteriores;
    // End of variables declaration//GEN-END:variables
}
